name: clean_onek1k
description: Dataset specific preprocessing steps.
arguments:
  - name: --input
    description: The path of the output file
    type: file
    example: data/onek1k.h5ad
    default: data/onek1k_cleaned.h5ad
    direction: input
  - name: --output
    description: The path of the output file
    type: file
    example: data/onek1k_cleaned.h5ad
    default: data/onek1k_cleaned.h5ad
    direction: output
  - name: --output_compression
    description: The compression format of the output file
    type: string
    example: gzip
    required: false
    
resources:
  - type: python_script
    path: script.py

engines:
  - type: native
runners:
  - type: executable
  - type: nextflow