functionality:
  name: download_onek1k
  # TODO: description for onek1k
  description: "download_onek1k..."
  arguments:
    - name: --output
      description: The path of the output file
      type: file
      example: onek1k1.h5ad
      default: data/onek1k1.h5ad
      direction: output
    # - name: --max_chunks
    #   description: The maximum number of chunks to download. Used for test purposes
    #   type: integer
    #   example: 5
    #   required: false
    - name: --output_compression
      description: The compression format of the output file
      type: string
      example: gzip
      required: false
      
  resources:
    - type: python_script
      path: script.py

platforms:
  - type: native

  # - type: docker
  #   image: patient_representation_img

  - type: nextflow
