name: sample_representation
description: "get patient representation..."
arguments: 
  - name: --output
    type: file
    example: combat_with_patient_representations.h5ad
    direction: output
    required: true
  - name: --input
    type: file
    example: combat_processed.h5ad
    direction: input
    required: true
  - name: --sample_key
    type: string
    example: "scRNASeq_sample_ID"
    required: true
  - name: --cell_type_key
    type: string
    example: Annotation_major_subset
    required: true
  - name: --batch_covariates
    type: string
    example: ["scRNASeq_sample_ID","Pool_ID"]
    multiple: true
    multiple_sep: ","
    required: true
  - name: --celltype_pseudobulk_sample_size_threshold
    type: integer
    default: 500
    required: false
  - name: --output_compression
    description: The compression format of the output file
    type: string
    example: gzip
    required: false

resources:
  - type: python_script
    path: script.py
test_resources:
  - type: python_script
    path: test.py
  - type: file
    path: "../../data/synthetic_processed.h5ad"
  - type: file
    path: "../../data/synthetic_metadata.csv" 

engines:
  - type: native
runners:
  - type: executable
  - type: nextflow