functionality:
  name: representation
  description: "get patient representation..."
  arguments: 
    - name: --output
      type: file
      example: combat_with_patient_representations.h5ad
      direction: output
      required: true
    - name: --input
      type: file
      example: combat.h5ad
      required: true
    - name: --sample_key
      type: string
      example: "scRNASeq_sample_ID"
      required: true
    - name: --cell_type_key
      type: string
      example: Annotation_major_subset
      required: true
    - name: --patient_state_key
      type: string
      example: Outcome
      required: true
    - name: --output_compression
      description: The compression format of the output file
      type: string
      example: gzip
      required: false
  
  resources:
    - type: python_script
      path: script.py

platforms:
  - type: native

  # - type: docker
  #   image: patient_representation_img
  
  - type: nextflow