name: clean_combat
description: |
  Perform the dataset-specific preprocessing steps.
  Dataset properties:
  - PBMC data from COVID-19 patients, healthy donors, and patients with other infections
  - 140 donors
  - ~800,000 cells
  - Multiomic data (in the benchmark, we focus on single-cell data)
  - Different conditions, and outcomes
  - 2 institutes where the data was generated, and several pools
arguments:
  - name: --input
    description: The path of the input file
    type: file
    example: data/combat.h5ad
    required: true
  - name: --output
    description: The path of the output file
    type: file
    default: data/combat_cleaned.h5ad
    direction: output
  - name: --output_compression
    description: The compression format of the output file
    type: string
    example: gzip
    required: false
    
resources:
  - type: python_script
    path: script.py
  - type: file
    path: ../../../data/ifn_1_score.tsv

engines:
  - type: native
runners:
  - type: executable
  - type: nextflow
