functionality:
  name: download_hlca
  description: "download_hlca..."
  # arguments:
  #   - type: file
  #     name: --dataset
  #     example: combat_processed.h5ad
      
  resources:
    - type: python_script
      path: download_hlca.py

platforms:
  - type: native

  # - type: docker
  #   image: patient_representation_img

  - type: nextflow
