name: preprocess
description: Preprocess the data in the same way for every dataset.
  - Normalize the data
  - Log-transform the data
  - Select HVGs
  - Run PCA
  - Run Harmony on PCA embeddings
  - Run scVI and scANVI
  - Calculate QC metrics on cell and sample level
  - Extract sample-level metadata
  - Save processed data and metadata
arguments: 
  - name: --output
    type: file
    example: combat_processed.h5ad
    direction: output
    required: true
  - name: --input
    type: file
    example: combat.h5ad
    direction: input
    required: true
  - name: --sample_key
    type: string
    example: "scRNASeq_sample_ID"
    required: true
  - name: --samples_metadata_cols
    type: string
    example: ["Source", "Outcome", "Death28", "Institute", "Pool_ID"]
    multiple: true
    multiple_sep: ","
    required: true
  - name: --batch_key
    description: The batch key to use for HVG selection
    type: string
    example: "Pool_ID"
    required: true
  - name: --batch_covariates
    description: The covariates to use for batch effect correction with Harmony, scVI, and scANVI
    type: string
    example: ["scRNASeq_sample_ID","Pool_ID"]
    multiple: true
    multiple_sep: ","
    required: false
  - name: --cell_type_key
    type: string
    example: Annotation_major_subset
    required: true
  - name: --sample_size_threshold
    description: The minimum number of cells a sample needs to have to be included in the analysis
    type: int
    default: 100
    required: false
  - name: --output_compression
    description: The compression format of the output file
    type: string
    example: gzip
    required: false
  - name: --output_metadata
    type: file
    example: combat_preprocessed_metadata.csv
    required: true
  
resources:
  - type: python_script
    path: script.py
test_resources:
  - type: python_script
    path: test.py

engines:
  - type: native
runners:
  - type: executable
  - type: nextflow
