functionality:
  name: preprocess
  description: "preprocess..."
  arguments: 
    - name: --output
      type: file
      example: combat_processed.h5ad
      direction: output
      required: true
    - name: --input
      type: file
      example: combat.h5ad
      direction: input
      required: true
    - name: --batch_covariates
      type: string
      example: ["scRNASeq_sample_ID","Pool_ID"]
      multiple: true
      multiple_sep: ","
      required: true
    - name: --batch_effect_covariate
      type: string
      example: "Pool_ID"
      required: true
    - name: --cell_type_key
      type: string
      example: Annotation_major_subset
      required: true
    - name: --output_compression
      description: The compression format of the output file
      type: string
      example: gzip
      required: false
    
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: "../../data/"

platforms:
  - type: native

  # - type: docker
  #   image: patient_representation_img

  - type: nextflow
