functionality:
  name: workflow
  description: |
    An example pipeline and project template.

    Multiple TSV files can be input, each with a 'column' identifier that
    should be extracted. All extracted columns are then collated again.
  arguments:
    - type: file
      name: --dataset

  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf

  dependencies: 
    - name: preprocess_combat
      repository: local
    - name: represent_combat
      repository: local

  repositories:
    - name: local
      type: local
platforms:
  - type: nextflow
