name: download_all
description: |
  Download all datasets required for the benchmark:
  - COMBAT: COVID-19 blood atlas
  - OneK1K: Single-cell RNA sequencing of 1,000 peripheral blood mononuclear cells (PBMCs)
  - Stephenson: COVID-19 PBMC dataset
  - HLCA: Human Lung Cell Atlas
arguments:
  - name: --output_dir
    type: string
    description: Directory where all datasets will be saved
    default: data
    required: true
  - name: --compression
    type: string
    description: Compression format for output files
    default: gzip
    required: false

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: download_all

dependencies:
  - name: download_combat
    repository: local
  - name: download_onek1k
    repository: local
  - name: download_stephenson
    repository: local
  - name: download_hlca
    repository: local

repositories:
  - name: local
    type: local

runners:
  - type: nextflow
