name: diffusionemd
description: >
  Apply Diffusion Earth Mover's Distance (DiffusionEMD) sample representation method

arguments:
  - type: file
    name: --input
    description: Path to the input data
    direction: input
    required: true
    example: "combat_processed.h5ad"

  - type: file
    name: --output
    description: Path to save the sample representations
    direction: output
    required: true
    example: "combat_diffusionemd_pca.csv"

  - type: string
    name: --sample_key
    description: Column name containing sample identifiers
    required: true
    example: "scRNASeq_sample_ID"

  - type: string
    name: --cell_type_key
    description: Column name containing cell type identifiers
    required: true
    example: "Annotation_major_subset"

  - type: string
    name: --layer
    description: Embedding in .obsm to build the kNN graph on
    required: true
    example: "X_pca"

  - type: integer
    name: --n_neighbors
    description: Number of neighbors for the kNN graph
    required: false
    default: 15

  - type: integer
    name: --n_scales
    description: Number of diffusion scales used by DiffusionCheb
    required: false
    default: 6

resources:
  - type: python_script
    path: script.py

engines:
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [highmem, lowcpu]
