functionality:
  name: download_combat
  description: "download_combat..."
  # arguments:
  #   - type: file
  #     name: --dataset
  #     example: combat_processed.h5ad
      
  resources:
    - type: bash_script
      path: download_combat.sh

platforms:
  - type: native

  # - type: docker
  #   image: "bash:4.0"

  - type: nextflow
